name: go_build

on: 
  push:
    branches:
      - main

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm64]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup go and release
        uses: wangyoucao577/go-release-action@v1.46
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           goos: ${{ matrix.goos }}
           goarch: ${{ matrix.goarch }}
           binary_name: "xqtx"
