name: Build and Publish Binary
on: [push] # 当有 push 操作时触发构建
jobs:
  build:
    runs-on: ubuntu-latest # 运行环境选择最新版本的 Ubuntu
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 拉取仓库代码到 runner
      
      - name: Set up Go
        uses: actions/setup-go@v1 # 设置 Go 语言环境
        
      - name: Install dependencies
        run: go mod download # 安装项目所需的依赖包
      
      - name: Build binary
        run: go build -o main . # 构建二进制文件
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1 # 上传构建好的二进制文件
        with:
          path: ./main # 指定要上传的文件路径
