name: go_build

on: 
  release:
    types: [created,published]

permissions:
    contents: write
    packages: write

jobs:
  build-go-binary:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1.46
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm64
        binary_name: "xqtx"
